MODULE MOD_BMD

USE SET_KND

IMPLICIT NONE

REAL(R8), ALLOCATABLE :: BMD_TEMB(:,:,:)
REAL(R8), ALLOCATABLE :: BMD_SALB(:,:,:)

REAL(R8), PARAMETER :: RHO0 = 1020._R8
INTEGER(I4)    :: BMD_NNEOS = 0

END MODULE MOD_BMD
