SUBROUTINE RMVSHALLOWINS 

USE SET_KND
USE IOUNITS
USE MYFRTPROF, ONLY : MYFRTPROF_WALL
USE OBS_STR
USE RUN, ONLY : CDATE, KLEVNM
USE GRD_STR
IMPLICIT NONE
REAL(R8) :: MSK4
INTEGER(I4) :: K,JVL,JP

#include "obs_events.h"

CALL MYFRTPROF_WALL('RMV_SHALLOW_INS: CHECK FOR SHALLOW ARGO',0)

IF(INS%NO.LE.0) THEN
   CALL MYFRTPROF_WALL('RMV_SHALLOW_INS: CHECK FOR SHALLOW ARGO',1)
   RETURN
ENDIF

!... CHECK LEVEL OF NO MOTION FOR EACH OBS
DO JVL=1,GRD%KM
   IF(GRD%DEP(JVL) .GT. SLA%DEP) THEN
      KLEVNM = JVL
      EXIT
   ENDIF
ENDDO
WRITE(IOUNOUT,*) ' MIN DEPTH LEVEL IS',SLA%DEP,&
             & ' M CORRESPONDING TO MODEL LEVEL',KLEVNM
WRITE(IOUNLOG,*) ' MIN DEPTH LEVEL IS',SLA%DEP,&
             & ' M CORRESPONDING TO MODEL LEVEL',KLEVNM
CYOBS4: DO K=1,INS%NO
   IF (INS%FLC(K) .EQ. 1) THEN
      MSK4=0._R8
      DO JP=1,NPQ
         MSK4=MSK4+GRD%MSK(INS%IB(K,JP),INS%JB(K,JP),KLEVNM)
      ENDDO

      IF(MSK4 .LT. 3.9_R8) THEN
         INS%FLC(K) = 0
         INS%EVE(K) = KEVE_TOOS
         CYCLE CYOBS4
      ENDIF
   ENDIF
ENDDO CYOBS4

WRITE(IOUNLOG,*) 
WRITE(IOUNLOG,*) ' NUMBER OF ARGO in SHALLOW AREA = ', &
             & COUNT(INS%EVE(1:INS%NO) .EQ. KEVE_TOOS)
WRITE(IOUNLOG,*) 

CALL FLUSH(IOUNLOG)

CALL MYFRTPROF_WALL('RMV_SHALLOW_INS: CHECK FOR SHALLOW ARGO',1)
END SUBROUTINE RMVSHALLOWINS
