SUBROUTINE SUMPI

USE SET_KND, ONLY : I4
#ifndef NOMPI
USE MPI
#endif
USE MPIREL
USE IOUNITS
USE RUN
USE OMP_LIB
USE GRD_STR
USE MOD_SORT

IMPLICIT NONE

INTEGER(KIND=I4) :: IERR, IRET
INTEGER(KIND=I4) :: IAUX, JI, NMPIDOMS, NTHRDS
INTEGER(KIND=I4) :: JJ,ROWX,COLMY
NAMELIST / MPILST / LLUSEMPI, NIOMASTER, NIOMASTERB
#ifdef NOMPI
INTEGER(KIND=I4), PARAMETER :: MPI_COMM_WORLD=1, MPI_SUCCESS=0
#endif

CHARACTER*(MPI_MAX_PROCESSOR_NAME) PROCNAME
INTEGER(KIND=I4) :: JX,JY,START,COUNTX,COUNTY,NUM_PROCS_ONMAP,NAME_LEN
REAL(R8), ALLOCATABLE :: NPROC_TEMP_SORT(:)

INTEGER(KIND=I4), ALLOCATABLE :: X2_ST(:), X2_EN(:), Y2_ST(:), Y2_EN(:), YMST(:),YMEN(:),XCST(:),XCEN(:)


CMPIDOM='    '

!... OPEN NAMELIST
OPEN(IOUNNAM,FILE='var_3d_nml',STATUS='OLD',IOSTAT=IERR)
IF(IERR.NE.0) CALL ABOR1('PROBLEMS OPENING NAMELIST')

!... SET DEFAULTS AND READ NAMELIST
LLUSEMPI=.FALSE.
NIOMASTER=1
NIOMASTERB=1

CALL POSNAM(IOUNNAM,'MPILST')
READ(IOUNNAM,MPILST)

!$OMP PARALLEL DEFAULT(SHARED)
NTHRDS = OMP_GET_NUM_THREADS()
!$OMP END PARALLEL

WRITE(IOUNOUT,*) 'NUMBER OF OMP THREADS  :', NTHRDS

IF(LLUSEMPI) THEN

!... INITIALIZE

#ifdef NOMPI
   CALL MPI_INIT(IERR)
#else
   CALL MPI_INIT(IERR)
   !CALL MPI_INIT_THREAD(MPI_THREAD_FUNNELED,IRET,IERR)
   !WRITE(IOUNLOG,*) ' MPI_INIT_THREAD RETURNED ', IRET
   !WRITE(IOUNLOG,*) ' MPI_THREAD_SINGLE :', MPI_THREAD_SINGLE
   !WRITE(IOUNLOG,*) ' MPI_THREAD_FUNNELED :', MPI_THREAD_FUNNELED
   !WRITE(IOUNLOG,*) ' MPI_THREAD_SERIALIZED :',  MPI_THREAD_SERIALIZED
   !WRITE(IOUNLOG,*) ' MPI_THREAD_MULTIPLE :', MPI_THREAD_MULTIPLE
#endif

   IF (IERR.NE.MPI_SUCCESS) CALL ABOR1('SUMPI: MPI_INIT ERROR')

!... GET THE NUMBER OF PROCESSES.

   CALL MPI_COMM_SIZE (MPI_COMM_WORLD, NPROCS, IERR)
   IF (IERR.NE.MPI_SUCCESS) CALL ABOR1('SUMPI: MPI_COMM_SIZE ERROR')

   CALL MPI_COMM_RANK (MPI_COMM_WORLD, MYPROC, IERR)
   IF (IERR.NE.MPI_SUCCESS) CALL ABOR1('SUMPI: MPI_COMM_SIZE ERROR')

   CALL MPI_GET_PROCESSOR_NAME(PROCNAME,NAME_LEN,IERR)

   WRITE(IOUNOUT,*)
   WRITE(IOUNOUT,*) 'NUMBER OF MPI PROCESSES:', NPROCS

   NMPIDOMS=NPROCS

   WRITE(CMPIDOM,'(I4.4)') MYPROC
   MYPROC=MYPROC+1

   LMPION=.TRUE.

ELSE

   WRITE(IOUNOUT,*)
   WRITE(IOUNOUT,*) 'SINGLE-PROCESS RUN'

   LMPION=.FALSE.
   NPROCS=1
   MYPROC=1
   NIOMASTER=1
   NIOMASTERB=1

ENDIF

!... INIT LOGFILE ACCORDINGLY
! NO I/O HAS TO BE DONE BEFORE THE CALL TO SULOGF
CALL SULOGF

IF(LMPION) THEN

   WRITE(IOUNLOG,*) "RUNNING ON PROC CALLED ",PROCNAME

   NXDOM=-1_I4
   NYDOM=-1_I4

   OPEN(UNIT=99,FILE='mpp_conf.dat',STATUS='OLD')
   READ(99,*) IAUX,NXDOM,NYDOM
   IF( IAUX .NE. NMPIDOMS ) CALL ABOR1('SUMPI: MISMATCH BETWEEN NUMBER OF DOMAINS AND MPI PROCS')
   IF( NXDOM .LE. 0 .OR.  NYDOM .LE. 0 .OR.  NXDOM*NYDOM .LT. NMPIDOMS ) CALL ABOR1('SUMPI: MISMATCH BETWEEN NX,NY AND DOMAINS')
    ALLOCATE( MP_SD(NPROCS), MP_SDST(NPROCS), MP_XST(NPROCS), MP_XEN(NPROCS), &
   & MP_YST(NPROCS), MP_YEN(NPROCS) )
   DO JI=1,NMPIDOMS
      READ(99,*) MP_SD(JI),MP_SDST(JI),MP_XST(JI),MP_XEN(JI),MP_YST(JI),MP_YEN(JI)
   ENDDO
   CLOSE(99)
   NN_DOMSTART=MP_SDST(MYPROC)


   ALLOCATE(PROC_XMED(NPROCS),PROC_YMED(NPROCS))
   ALLOCATE(PROC_XMED_ORDERED(NPROCS),PROC_YMED_ORDERED(NPROCS))
   ALLOCATE(PROC_WE(NPROCS),PROC_EA(NPROCS),PROC_NO(NPROCS),PROC_SO(NPROCS))
   ALLOCATE(PROC_POSX_IN_MAP(NPROCS),PROC_POSY_IN_MAP(NPROCS))
   ALLOCATE(MAP_XMED(NXDOM),MAP_YMED(NYDOM))
   ALLOCATE(MPI_MAP(NXDOM,NYDOM))
   
   ALLOCATE(NPROC_TEMP_SORT(NPROCS))
   
   PROC_XMED(:)= INT((MP_XST(:)+ MP_XEN(:))/2)
   PROC_YMED(:)= INT((MP_YST(:)+ MP_YEN(:))/2)
   
   NPROC_TEMP_SORT(:)=REAL(PROC_XMED(:),R4)
   CALL SORT(NPROC_TEMP_SORT,NPROCS)
   PROC_XMED_ORDERED(:)=INT(NPROC_TEMP_SORT(:),I4)
   
   NPROC_TEMP_SORT(:)=REAL(PROC_YMED(:),R4)
   CALL SORT(NPROC_TEMP_SORT,NPROCS)
   PROC_YMED_ORDERED(:)=INT(NPROC_TEMP_SORT(:),I4)
   
   DEALLOCATE(NPROC_TEMP_SORT)
   
   MAP_XMED(1)=PROC_XMED_ORDERED(1)
   MAP_YMED(1)=PROC_YMED_ORDERED(1)
   
   COUNTX=1
   COUNTY=1
   DO JI=2,NPROCS
      IF (PROC_XMED_ORDERED(JI-1) .NE. PROC_XMED_ORDERED(JI)) THEN
         COUNTX=COUNTX+1
         IF (COUNTX .GT. NXDOM) THEN
               WRITE(IOUNLOG,*) PROC_XMED_ORDERED
               WRITE(IOUNLOG,*)    "DOMAINS READ > NXDOM !! please check mpp_conf.dat "
               STOP
           ENDIF
           MAP_XMED(COUNTX)=PROC_XMED_ORDERED(JI)
      ENDIF
      IF (PROC_YMED_ORDERED(JI-1) .NE. PROC_YMED_ORDERED(JI)) THEN
         COUNTY=COUNTY+1
         IF (COUNTY .GT. NYDOM) THEN
               WRITE(IOUNLOG,*) "DOMAINS READ > NYDOM !! please check mpp_conf.dat "
               STOP
           ENDIF
           MAP_YMED(COUNTY)=PROC_YMED_ORDERED(JI)
      ENDIF
   ENDDO
   
   IF((COUNTX .NE. NXDOM) .OR. (COUNTY .NE. NYDOM)) THEN
      WRITE(IOUNLOG,*) "DOMAINS READ < NXDOM,NYDOM !!! please check mpp_conf.dat"
       STOP
   ENDIF
   
   
   PROC_POSX_IN_MAP(:)=-1
   PROC_POSY_IN_MAP(:)=-1
   MPI_MAP(:,:)=-1
   
   DO JI=1,NPROCS
      DO JX=1,NXDOM
         if (PROC_XMED(JI) .EQ. MAP_XMED(JX)) THEN
         PROC_POSX_IN_MAP(JI)=JX
         CONTINUE
         ENDIF
      ENDDO
      IF(PROC_POSX_IN_MAP(JI) .EQ. -1) THEN
           WRITE(IOUNLOG,*) "PROC=JI-1->",JI-1," MISMATCH X DIVISIONS AND DOMAINS!!! please check mpp_conf.dat"
           STOP
      ENDIF
      DO JY=1,NYDOM
         IF (PROC_YMED(JI) .EQ. MAP_YMED(JY)) THEN
         PROC_POSY_IN_MAP(JI)=JY
         CONTINUE
         ENDIF
      ENDDO
      IF(PROC_POSY_IN_MAP(JI) .EQ. -1) THEN
               WRITE(IOUNLOG,*) "PROC=JI-1->",JI-1," MISMATCH Y DIVISION AND DOMAINS!!! please check mpp_conf.dat"
           STOP
       ENDIF
   
      MPI_MAP(PROC_POSX_IN_MAP(JI),PROC_POSY_IN_MAP(JI))=JI
   ENDDO
   
   
   PROC_WE(:)=-1
   PROC_EA(:)=-1
   PROC_NO(:)=-1
   PROC_SO(:)=-1
   
   DO JI=1,NPROCS
      !..NEXT EA PROC (INCREASE X)
      IF(PROC_POSX_IN_MAP(JI).LT.NXDOM) THEN
         PROC_EA(JI)=MPI_MAP(PROC_POSX_IN_MAP(JI)+1,PROC_POSY_IN_MAP(JI))
      ELSE
         PROC_EA(JI)=MPI_MAP(1,PROC_POSY_IN_MAP(JI))
      ENDIF
      !IF (PROC_EA(JI).EQ. -1) PROC_EA(JI)=MPI_MAP(PROC_POSX_IN_MAP(JI),PROC_POSY_IN_MAP(JI))
   
      !..NEXT WE PROC (DECREASE X)
   
      IF(PROC_POSX_IN_MAP(JI).GT.1) THEN
         PROC_WE(JI)=MPI_MAP(PROC_POSX_IN_MAP(JI)-1,PROC_POSY_IN_MAP(JI))
      ELSE
         PROC_WE(JI)=MPI_MAP(NXDOM,PROC_POSY_IN_MAP(JI))
      ENDIF
      !IF (PROC_WE(JI).EQ. -1) PROC_WE(JI)=MPI_MAP(PROC_POSX_IN_MAP(JI),PROC_POSY_IN_MAP(JI))
   
   
      !..NEXT NO PROC (INCREASE Y) !NO BOUNDARY CONDITION
   
      IF(PROC_POSY_IN_MAP(JI).LT.NYDOM) THEN
         PROC_NO(JI)=MPI_MAP(PROC_POSX_IN_MAP(JI),PROC_POSY_IN_MAP(JI)+1)
      ELSE
         PROC_NO(JI)=MPI_MAP(PROC_POSX_IN_MAP(JI),PROC_POSY_IN_MAP(JI))
      ENDIF
      !IF (PROC_NO(JI).EQ. -1) PROC_NO(JI)=MPI_MAP(PROC_POSX_IN_MAP(JI),PROC_POSY_IN_MAP(JI))
   
   
      !..NEXT SO PROC (DECREASE Y)
   
      IF(PROC_POSY_IN_MAP(JI).GT.1) THEN
         PROC_SO(JI)=MPI_MAP(PROC_POSX_IN_MAP(JI),PROC_POSY_IN_MAP(JI)-1)
      ELSE
         PROC_SO(JI)=MPI_MAP(PROC_POSX_IN_MAP(JI),PROC_POSY_IN_MAP(JI))
      ENDIF
      !IF (PROC_SO(JI).EQ. -1) PROC_SO(JI)=MPI_MAP(PROC_POSX_IN_MAP(JI),PROC_POSY_IN_MAP(JI))
   ENDDO
   
   WE_BOUNDARY=.FALSE.
   EA_BOUNDARY=.FALSE.
   
   IF (PROC_POSX_IN_MAP(MYPROC) .EQ. 1_I4 .AND. PROC_WE(MYPROC) .NE. -1_I4) THEN
    IF (PROC_POSX_IN_MAP(PROC_WE(MYPROC)) .EQ. NXDOM) WE_BOUNDARY=.TRUE.
   ENDIF
   IF (PROC_POSX_IN_MAP(MYPROC) .EQ. NXDOM .AND. PROC_EA(MYPROC) .NE. -1_I4) THEN
   IF (PROC_POSX_IN_MAP(PROC_EA(MYPROC)) .EQ. 1_I4) EA_BOUNDARY=.TRUE.
   ENDIF
   
   SO_BOUNDARY=.FALSE.
   NO_BOUNDARY=.FALSE.
   
   IF (PROC_POSY_IN_MAP(MYPROC) .EQ. 1_I4) SO_BOUNDARY=.TRUE.
   
   IF (PROC_POSY_IN_MAP(MYPROC) .EQ. NYDOM ) NO_BOUNDARY=.TRUE.
   
   
   
   WRITE(IOUNLOG,*) " LAYOUT OF PROCESSORS AS READ, LAND is -1"
   WRITE(IOUNLOG,*) ""
   11210 FORMAT(A)
   11211 FORMAT(A,I3,A)
   11212 FORMAT(A,I4,A,I4,A)
   DO JY=NYDOM,1,-1
       DO JX=1,NXDOM
           WRITE(IOUNLOG,11210,ADVANCE="no") " -----------------"
       ENDDO
       WRITE(IOUNLOG,*) ""
       DO JX=1,NXDOM
           IF (MYPROC .EQ.MPI_MAP(JX,JY)) THEN
           WRITE(IOUNLOG,11211,ADVANCE="no") "    -->",MPI_MAP(JX,JY)," <--   |"
           ELSE
           WRITE(IOUNLOG,11211,ADVANCE="no") "       ",MPI_MAP(JX,JY),"       |"
           ENDIF
       ENDDO
       WRITE(IOUNLOG,*) ""
       DO JX=1,NXDOM
           WRITE(IOUNLOG,11212,ADVANCE="no") " (x=",MAP_XMED(JX),",y=",MAP_YMED(JY),") |"
       ENDDO
      WRITE(IOUNLOG,*) ""
   
   
      IF(MPI_MAP(1,JY) .EQ. -1_I4) THEN
         WRITE(IOUNLOG,11210,ADVANCE="no") "                 |"
      ELSE IF ( PROC_WE(MPI_MAP(1,JY)) .NE. -1_I4) THEN
         WRITE(IOUNLOG,11210,ADVANCE="no") "<< WE            |"
      ELSE
         WRITE(IOUNLOG,11210,ADVANCE="no") "                 |"
      ENDIF
      DO JX=2,NXDOM-1
           WRITE(IOUNLOG,11210,ADVANCE="no") "                 |"
      ENDDO
      IF(MPI_MAP(NXDOM,JY) .EQ. -1_I4) THEN
         WRITE(IOUNLOG,11210,ADVANCE="no") "                 |"
      ELSE IF ( PROC_EA(MPI_MAP(NXDOM,JY)) .NE. -1_I4) THEN
         WRITE(IOUNLOG,11210,ADVANCE="no") "            EA >>|"
      ELSE
         WRITE(IOUNLOG,11210,ADVANCE="no") "                 |"
      ENDIF
   
      WRITE(IOUNLOG,*) ""
   ENDDO
   DO JX=1,NXDOM
   WRITE(IOUNLOG,11210,ADVANCE="no") " -----------------"
   ENDDO
   WRITE(IOUNLOG,*) ""
   WRITE(IOUNLOG,*) ""
   
   
   
   
   NUM_PROCS_ONMAP=0
      DO JX=1,NXDOM
      DO JY=1,NYDOM
         IF(MPI_MAP(JX,JY) .NE. -1) NUM_PROCS_ONMAP=NUM_PROCS_ONMAP+1
      ENDDO
      ENDDO
   
   IF(NUM_PROCS_ONMAP .NE. NPROCS) STOP  "SOME DOMAINS ARE REPLICATED!!! please check mpp_conf.dat"
   
   DO JI=1,NPROCS
      IF (MPI_MAP(PROC_POSX_IN_MAP(JI),PROC_POSY_IN_MAP(JI)) .EQ. -1) THEN
       WRITE(IOUNLOG,*)"ERROR IN MAPPING THE DOMAIN NUM =",JI
       STOP
       ENDIF
   ENDDO
   
   
   WRITE(IOUNLOG,*) "THIS DOMAIN IS",MYPROC
   WRITE(IOUNLOG,*) "WE PROC IS NUM",PROC_WE(MYPROC)
   WRITE(IOUNLOG,*) "EA PROC IS NUM",PROC_EA(MYPROC)
   WRITE(IOUNLOG,*) "NO PROC IS NUM",PROC_NO(MYPROC)
   WRITE(IOUNLOG,*) "SO PROC IS NUM",PROC_SO(MYPROC)
   
   
   ALLOCATE(LOCAL_OVERLAP_WE_XST(NPROCS),LOCAL_OVERLAP_EA_XST(NPROCS),LOCAL_OVERLAP_SO_YST(NPROCS),LOCAL_OVERLAP_NO_YST(NPROCS))
   ALLOCATE(LOCAL_OVERLAP_WE_XEN(NPROCS),LOCAL_OVERLAP_EA_XEN(NPROCS),LOCAL_OVERLAP_SO_YEN(NPROCS),LOCAL_OVERLAP_NO_YEN(NPROCS))
   ALLOCATE(LOCAL_OVERLAP_SO_XST(NPROCS),LOCAL_OVERLAP_SO_XEN(NPROCS),LOCAL_OVERLAP_NO_XST(NPROCS),LOCAL_OVERLAP_NO_XEN(NPROCS))
   ALLOCATE(WE_BOUND_ARRAY(NPROCS),EA_BOUND_ARRAY(NPROCS),NO_BOUND_ARRAY(NPROCS),SO_BOUND_ARRAY(NPROCS))
   ALLOCATE( X2_ST(NPROCS), X2_EN(NPROCS), Y2_ST(NPROCS), Y2_EN(NPROCS) )! NOT OVERLAPPING REGION
   ALLOCATE( YMST(NPROCS), YMEN(NPROCS), XCST(NPROCS), XCEN(NPROCS) ) ! OVERLAPPING REGION
   
   WE_BOUND_ARRAY(:)=.FALSE.
   EA_BOUND_ARRAY(:)=.FALSE.
   NO_BOUND_ARRAY(:)=.FALSE.
   SO_BOUND_ARRAY(:)=.FALSE.
   
   DO JJ=1,NPROCS
   IF (PROC_POSX_IN_MAP(JJ) .EQ. 1_I4 ) WE_BOUND_ARRAY(JJ)=.TRUE.
   IF (PROC_POSX_IN_MAP(JJ) .EQ. NXDOM) EA_BOUND_ARRAY(JJ)=.TRUE.
   IF (PROC_POSY_IN_MAP(JJ) .EQ. 1_I4 ) SO_BOUND_ARRAY(JJ)=.TRUE.
   IF (PROC_POSY_IN_MAP(JJ) .EQ. NYDOM) NO_BOUND_ARRAY(JJ)=.TRUE.
   ENDDO
   
   !WRITE(IOUNLOG,*) "WE_BOUND_ARRAY",WE_BOUND_ARRAY
   !WRITE(IOUNLOG,*) "SO_BOUND_ARRAY",EA_BOUND_ARRAY
   !WRITE(IOUNLOG,*) "SO_BOUND_ARRAY",SO_BOUND_ARRAY
   !WRITE(IOUNLOG,*) "NO_BOUND_ARRAY",NO_BOUND_ARRAY
   !RITE(IOUNLOG,*) MP_XST
   !WRITE(IOUNLOG,*) MP_XEN
   !WRITE(IOUNLOG,*) MP_YST
   !WRITE(IOUNLOG,*) MP_YEN
   
   !... FIND overlapping
   
   DO JJ=1,NPROCS
   WRITE(IOUNLOG,*) JJ
       IF( .NOT. WE_BOUND_ARRAY(JJ)) THEN
           IF(PROC_WE(JJ) .NE. -1) THEN
               X2_ST(JJ)=MP_XEN(PROC_WE(JJ))
           ELSE
               ROWX=PROC_POSX_IN_MAP(JJ)-1
               DO  JY=1,NYDOM
                   IF(MPI_MAP(ROWX,JY) .NE. -1) THEN
                       X2_ST(JJ)=MP_XEN(MPI_MAP(ROWX,JY))
                       CONTINUE
                   ENDIF
               ENDDO
           ENDIF
       ELSE
           X2_ST(JJ)=MP_XST(JJ)
       ENDIF
       IF( .NOT. EA_BOUND_ARRAY(JJ)  ) THEN
           IF(PROC_EA(JJ) .NE. -1) THEN
               X2_EN(JJ)=MP_XST(PROC_EA(JJ))
           ELSE
               ROWX=PROC_POSX_IN_MAP(JJ)+1
               DO  JY=1,NYDOM
                   IF(MPI_MAP(ROWX,JY) .NE. -1) THEN
                       X2_EN(JJ)=MP_XST(MPI_MAP(ROWX,JY))
                       CONTINUE
                   ENDIF
               ENDDO
           ENDIF
       ELSE
           X2_EN(JJ)=MP_XEN(JJ)
       ENDIF
       IF( .NOT. SO_BOUND_ARRAY(JJ) ) THEN
           IF(PROC_SO(JJ) .NE. -1 ) THEN
               Y2_ST(JJ)=MP_YEN(PROC_SO(JJ))
           ELSE
               COLMY=PROC_POSY_IN_MAP(JJ)-1
   
               DO  JX=1,NXDOM
                   IF(MPI_MAP(JX,COLMY) .NE. -1) THEN
                       Y2_ST(JJ)=MP_YEN(MPI_MAP(JX,COLMY))
                       CONTINUE
                   ENDIF
               ENDDO
           ENDIF
       ELSE
           Y2_ST(JJ)=MP_YST(JJ)
       ENDIF
       IF( .NOT. NO_BOUND_ARRAY(JJ) ) THEN
           IF(PROC_NO(JJ) .NE. -1 ) THEN
               Y2_EN(JJ)=MP_YST(PROC_NO(JJ))
           ELSE
               COLMY=PROC_POSY_IN_MAP(JJ)+1
               DO  JX=1,NXDOM
                   IF(MPI_MAP(JX,COLMY) .NE. -1) THEN
                       Y2_EN(JJ)=MP_YST(MPI_MAP(JX,COLMY))
                       CONTINUE
                   ENDIF
               ENDDO
           ENDIF
       ELSE
           Y2_EN(JJ)=MP_YEN(JJ)
       ENDIF
   ENDDO
   
   
   DO JJ=1,NPROCS
       IF( .NOT. EA_BOUND_ARRAY(JJ)) THEN
           XCST(JJ)=X2_EN(JJ)
           XCEN(JJ)=MP_XEN(JJ)
       ELSE
           XCST(JJ)=MP_XEN(JJ)
           XCEN(JJ)=MP_XEN(JJ)
       ENDIF
       IF( .NOT. NO_BOUND_ARRAY(JJ) ) THEN
           YMST(JJ)=Y2_EN(JJ)
           YMEN(JJ)=MP_YEN(JJ)
       ELSE
           YMST(JJ)=MP_YEN(JJ)
           YMEN(JJ)=MP_YEN(JJ)
       ENDIF
   ENDDO
   
   
   DO JJ=1,NPROCS
   
           LOCAL_OVERLAP_WE_XST(JJ)=1
           LOCAL_OVERLAP_WE_XEN(JJ)=X2_ST(JJ)-MP_XST(JJ)+1
           LOCAL_OVERLAP_EA_XST(JJ)=XCST(JJ)-MP_XST(JJ)+1
           LOCAL_OVERLAP_EA_XEN(JJ)=XCEN(JJ)-MP_XST(JJ)+1
   
           LOCAL_OVERLAP_SO_YST(JJ)=1
           LOCAL_OVERLAP_SO_YEN(JJ)=Y2_ST(JJ)-MP_YST(JJ)+1
           LOCAL_OVERLAP_NO_YST(JJ)=Y2_EN(JJ)-MP_YST(JJ)+1 !YMST(JJ)-MP_YST(JJ)+1
           LOCAL_OVERLAP_NO_YEN(JJ)=MP_YEN(JJ)-MP_YST(JJ)+1
   
           LOCAL_OVERLAP_SO_XST(JJ)=1                         !WILL BE MODIFIED FOR BOUNDARY EXTENSION
           LOCAL_OVERLAP_SO_XEN(JJ)=MP_XEN(JJ) -MP_XST(JJ)+1     !WILL BE MODIFIED FOR BOUNDARY EXTENSION (GRD#IM will change)
           LOCAL_OVERLAP_NO_XST(JJ)=1                             !WILL BE MODIFIED FOR BOUNDARY EXTENSION
           LOCAL_OVERLAP_NO_XEN(JJ)=MP_XEN(JJ) -MP_XST(JJ)+1                     !WILL BE MODIFIED FOR BOUNDARY EXTENSION
   
   ENDDO
   
   
   
   !---------------
   !DONE
   !------------
   !WRITE(IOUNLOG,*) "LOCAL_OVERLAP_WE_XST",LOCAL_OVERLAP_WE_XST
   !WRITE(IOUNLOG,*) "LOCAL_OVERLAP_WE_XEN",LOCAL_OVERLAP_WE_XEN
   !WRITE(IOUNLOG,*) "LOCAL_OVERLAP_EA_XST",LOCAL_OVERLAP_EA_XST
   !WRITE(IOUNLOG,*) "LOCAL_OVERLAP_EA_XEN",LOCAL_OVERLAP_EA_XEN
   !WRITE(IOUNLOG,*) "LOCAL_OVERLAP_SO_YST",LOCAL_OVERLAP_SO_YST
   !WRITE(IOUNLOG,*) "LOCAL_OVERLAP_SO_YEN",LOCAL_OVERLAP_SO_YEN
   !WRITE(IOUNLOG,*) "LOCAL_OVERLAP_NO_YST",LOCAL_OVERLAP_NO_YST
   !WRITE(IOUNLOG,*) "LOCAL_OVERLAP_NO_YEN",LOCAL_OVERLAP_NO_YEN
   
   
   
   DEALLOCATE( X2_ST, X2_EN, Y2_ST, Y2_EN ,XCST,XCEN,YMST,YMEN)
   DEALLOCATE(PROC_XMED_ORDERED,PROC_YMED_ORDERED,MAP_XMED,MAP_YMED,PROC_POSX_IN_MAP,PROC_POSY_IN_MAP)

ELSE
   NN_DOMSTART=1
ENDIF

!... REPORT TIME VARS

WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' THE PROGRAM HAS BEEN CALLED AS FOLLOWS:'
WRITE(IOUNLOG,*) TRIM(CARGS)
WRITE(IOUNLOG,*)
WRITE(IOUNLOG,*) ' ANALYSIS DATE         :',IANDATE
WRITE(IOUNLOG,*) ' ANALYSIS TIME         :',IANTIME
WRITE(IOUNLOG,*) ' ASSIMILATION WINDOW   :',IANTW
WRITE(IOUNLOG,*) ' ASSIM WINDOW CENTERED :',LL_TWCENTERED
WRITE(IOUNLOG,*) ' YY MM DD              :   ',IANYY,IANMM,IANDD
WRITE(IOUNLOG,*) ' HH MIN                :   ',IANHH,IANMI
WRITE(IOUNLOG,*) ' SECONDS               :   ',ZANSS
WRITE(IOUNLOG,*) ' JULIAN DAY            :   ',ZJULIAN
WRITE(IOUNLOG,*) ' JULIAN DAY  START     :   ',ZJULSTART
WRITE(IOUNLOG,*) ' JULIAN DAY  END       :   ',ZJULEND
WRITE(IOUNLOG,*) ' JULIAN DAY SINCE  1950:   ',ZANJUL1950
WRITE(IOUNLOG,*) ' JULIAN DAY START  1950:   ',ZJULSTART-ZJUL1950
WRITE(IOUNLOG,*) ' JULIAN DAY END    1950:   ',ZJULEND-ZJUL1950
WRITE(IOUNLOG,*) ' JULIAN DAY BEG.MM     :   ',ZJULSTARTMM
WRITE(IOUNLOG,*) ' JULIAN DAY BEG.MM 1950:   ',ZJULSTARTMM-ZJUL1950

WRITE(IOUNLOG,*)

!... REPORT THE STATUS IN THE LOGFILE

WRITE(IOUNLOG,*) ' ----------------------------------------'
WRITE(IOUNLOG,*) ' :: ROUTINE SUMPI : MPI INITIALIZATION ::'
WRITE(IOUNLOG,*) ' ----------------------------------------'
WRITE(IOUNLOG,*) ' LLUSEMPI   ',LLUSEMPI
WRITE(IOUNLOG,*) ' LMPION     ',LMPION
WRITE(IOUNLOG,*) ' NPROCS     ',NPROCS
WRITE(IOUNLOG,*) ' MYPROC     ',MYPROC
WRITE(IOUNLOG,*) ' NIOMASTER  ',NIOMASTER
WRITE(IOUNLOG,*) ' NIOMASTERB ',NIOMASTERB
WRITE(IOUNLOG,*) ' ----------------------------------------'

RETURN
END SUBROUTINE SUMPI
